### ISSUE TITLE
Consider using {pkgfiles}

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2md#12]
The job of the [pkgfiles](https://github.com/krlmlr/pkgfiles) package is to classify files in an R project according to their use. It helps distinguishing R scripts from other files. Using it would relieve {roxygen2md} from the responsibility to enumerate and filter files.

Most useful after https://github.com/krlmlr/pkgfiles/issues/1 is implemented.

Needs some mulling over, shouldn't delay the CRAN release.

**Comment by IndrajeetPatil** [comment]
Since `{pkgfiles}` is now an archived repo, I am assuming this is no longer relevant?
