### ISSUE TITLE
Release roxygen2md 1.0.0

### ISSUE THREAD

**Issue by krlmlr** [r-lib/roxygen2md#13]
Prepare for release: 
 
* [x] Check that description is informative 
* [x] Check licensing of included files 
* [x] `usethis::use_cran_comments()` 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] Polish pkgdown reference index 
* [ ] Draft blog post 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('major')` 
* [x] Update `cran-comments.md` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()` 
* [x] `usethis::use_news()` 
* [x] Update install instructions in README 
* [ ] Finish blog post 
* [ ] Tweet 
* [ ] Add link to blog post in pkgdown news menu

**Comment by IndrajeetPatil** [comment]
Since `{roxygen2md}` 1.0.0 is on CRAN, I think this can be closed?
