### ISSUE TITLE
docs in man-roxygen are not converted

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/roxygen2md#3]
I have a `man-roxygen` directory that is not touched by the conversion. Should be easy to fix with a PR.

**Comment by krlmlr** [comment]
Thanks. Happy to review.

**Comment by jayhesselberth** [comment]
Actually `man-roxygen` includes via `@template` are not parsed correctly at all (they still appear as markdown in the Rd files). This isn't documented in `roxygen/markdown.md`; maybe it's an upstream problem?

**Comment by krlmlr** [comment]
I've seen this too: https://github.com/krlmlr/dplyr/commit/89b892f9aecd850d1484791c6f826b8e7e652a7b#commitcomment-20813612. Will report here, but please feel free to submit a PR if you have it. (If not, I'm happy to do it myself.)

**Comment by krlmlr** [comment]
Now in klutometis/roxygen#594.

**Comment by jayhesselberth** [comment]
I posted a workaround in https://github.com/klutometis/roxygen/issues/594. You can add an `@md` tag to the template and get it to render.
