### ISSUE TITLE
add transformers for \emph, \bold and \url

### ISSUE THREAD

**Issue by hturner** [r-lib/roxygen2md#5]
Thanks for a useful tool! I added a few extra transformers to catch some common cases in my roxygen documentation and it would be useful if these could be added:

\emph{...} to *...*
\bold{...} to **...**
\url{...} to ...

With these additional transformers, the main thing I had to do manually was transform old markup spread over multiple lines, e.g.

    #' `Boston`, `Cleveland`, `Detroit`, `Milwaukee`, \code{New
    #' York}, `Toronto`. 

Would be even better if the transformers could fix these too!

**Comment by krlmlr** [comment]
Emphasis and URLs should be easy to implement, detecting markup spread over multiple lines not so much. Would you like to contribute a PR?
