### ISSUE TITLE
Export utility string to string translation utility

### ISSUE THREAD

**Issue by alexpghayes** [r-lib/roxygen2md#9]
I would love a function `roxygen_text_to_md()` to work with strings directly.

```r
roxygen_text_to_md("And here we have \emph{italics} in some text.")
#> [1] "And here we have *italics* in some text."
```

This would be useful when translating old documentation to markdown when the old documentation needs additional processing before being written into `roxygen2` comments, or when it won't live in `roxygen2` comments (i.e. gets pulled from another file/etc via a `@template` or `@evalRd` tag).

**Comment by krlmlr** [comment]
Closed in #10.
